import { QuestionConfig, SectionConfig, ArchetypeConfig } from '@/types';

// Survey Section Configurations
export const SURVEY_SECTIONS: SectionConfig[] = [
  {
    id: 'foundation',
    title: 'Section A',
    subtitle: 'The Foundation',
    introTitle: "Let's start with the basics.",
    introDescription:
      'This section helps us understand who you are, what tools you use daily, and where technology helps—or gets in the way.',
    questions: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12'],
  },
  {
    id: 'friction',
    title: 'Section B',
    subtitle: 'The Friction',
    introTitle: "Now let's talk about the friction.",
    introDescription:
      "We're looking for the tasks that drain your energy—the repetitive work that feels like walking through mud. Be honest; this is where we find the opportunities.",
    questions: ['q13', 'q14', 'q15', 'q16', 'q17', 'q18', 'q19', 'q20', 'q21', 'q22', 'q23'],
  },
  {
    id: 'ai-sentiment',
    title: 'Section C',
    subtitle: 'AI Sentiment',
    introTitle: "Let's talk about AI.",
    introDescription:
      "No judgment here—whether you're a daily user or completely skeptical, we want to understand your honest perspective.",
    questions: ['q24', 'q25', 'q26', 'q27', 'q28', 'q29', 'q30', 'q31', 'q32'],
  },
  {
    id: 'magic-button',
    title: 'Section D',
    subtitle: 'The Magic Button',
    introTitle: "Last section—let's dream a little.",
    introDescription:
      'If you could snap your fingers and change one thing about how you work, what would it be?',
    questions: ['q33', 'q34', 'q35', 'q36'],
  },
];

// All Survey Questions
export const SURVEY_QUESTIONS: Record<string, QuestionConfig> = {
  q1: {
    id: 'q1',
    key: 'q1_name',
    section: 'foundation',
    type: 'text',
    question: 'Name',
    placeholder: 'Your full name',
    required: true,
    validation: { minLength: 2 },
  },
  q2: {
    id: 'q2',
    key: 'q2_email',
    section: 'foundation',
    type: 'email',
    question: 'Email',
    placeholder: 'you@autside.com',
    required: true,
  },
  q3: {
    id: 'q3',
    key: 'q3_role',
    section: 'foundation',
    type: 'dropdown',
    question: "What's your role?",
    required: true,
    options: [
      { value: 'production-designer', label: 'Production Designer' },
      { value: 'senior-production-designer', label: 'Senior Production Designer' },
      { value: 'art-director', label: 'Art Director' },
      { value: 'creative-director', label: 'Creative Director' },
      { value: 'account-coordinator', label: 'Account Coordinator' },
      { value: 'account-manager', label: 'Account Manager' },
      { value: 'account-director', label: 'Account Director' },
      { value: 'media-production-specialist', label: 'Media Production Specialist' },
      { value: 'studio-manager', label: 'Studio Manager' },
      { value: 'founder-leadership', label: 'Founder / Leadership' },
      { value: 'other', label: 'Other (specify)' },
    ],
  },
  q4: {
    id: 'q4',
    key: 'q4_tenure',
    section: 'foundation',
    type: 'radio',
    question: 'How long have you been in your current role?',
    required: true,
    options: [
      { value: 'less-than-6-months', label: 'Less than 6 months' },
      { value: '6-months-1-year', label: '6 months – 1 year' },
      { value: '1-2-years', label: '1 – 2 years' },
      { value: '2-5-years', label: '2 – 5 years' },
      { value: '5-plus-years', label: '5+ years' },
    ],
  },
  q5: {
    id: 'q5',
    key: 'q5_tools',
    section: 'foundation',
    type: 'multi-select',
    question: 'What tools do you use daily?',
    required: true,
    validation: { minSelections: 1 },
    options: [
      { value: 'adobe-photoshop', label: 'Adobe Photoshop' },
      { value: 'adobe-illustrator', label: 'Adobe Illustrator' },
      { value: 'adobe-indesign', label: 'Adobe InDesign' },
      { value: 'adobe-after-effects', label: 'Adobe After Effects' },
      { value: 'adobe-premiere-pro', label: 'Adobe Premiere Pro' },
      { value: 'figma', label: 'Figma' },
      { value: 'canva', label: 'Canva' },
      { value: 'microsoft-powerpoint', label: 'Microsoft PowerPoint' },
      { value: 'microsoft-excel', label: 'Microsoft Excel' },
      { value: 'google-slides', label: 'Google Slides' },
      { value: 'google-sheets', label: 'Google Sheets' },
      { value: 'slack', label: 'Slack' },
      { value: 'microsoft-teams', label: 'Microsoft Teams' },
      { value: 'asana', label: 'Asana' },
      { value: 'monday', label: 'Monday.com' },
      { value: 'frame-io', label: 'Frame.io' },
      { value: 'dropbox', label: 'Dropbox' },
      { value: 'google-drive', label: 'Google Drive' },
      { value: 'box', label: 'Box' },
      { value: 'other', label: 'Other (specify)' },
    ],
  },
  q6: {
    id: 'q6',
    key: 'q6_tech_walls',
    section: 'foundation',
    type: 'multi-select',
    question: 'Where do you hit a "Tech Wall"?',
    description: 'Select any friction points you experience regularly.',
    required: false,
    conditionalOn: { questionKey: 'q5_tools', showWhenHasValue: true },
    options: [
      { value: 'adobe-powerpoint-conversions', label: 'Adobe → PowerPoint conversions' },
      { value: 'wrong-file-formats', label: 'Receiving files in wrong formats' },
      { value: 'marking-approvals', label: 'Marking up approvals and revisions' },
      { value: 'asset-searching', label: 'Searching the server for assets' },
      { value: 'version-control', label: 'Version control confusion' },
      { value: 'file-naming', label: 'File naming inconsistencies' },
      { value: 'handoff-miscommunication', label: 'Handoff miscommunication' },
      { value: 'software-compatibility', label: 'Software compatibility issues' },
      { value: 'other', label: 'Other (specify)' },
    ],
  },
  q7: {
    id: 'q7',
    key: 'q7_work_type',
    section: 'foundation',
    type: 'radio',
    question: 'What type of work fills most of your day?',
    required: true,
    options: [
      { value: 'digital-social', label: 'Digital / Social content' },
      { value: 'print-in-store', label: 'Print / In-store materials' },
      { value: 'video-animation', label: 'Video / Animation' },
      { value: 'presentation-decks', label: 'Presentation decks' },
      { value: 'brand-development', label: 'Brand development' },
      { value: 'campaign-strategy', label: 'Campaign strategy' },
      { value: 'account-client-management', label: 'Account / Client management' },
      { value: 'mix-of-everything', label: 'Mix of everything' },
    ],
  },
  q8: {
    id: 'q8',
    key: 'q8_primary_client',
    section: 'foundation',
    type: 'text',
    question: 'Who is your primary client or account?',
    placeholder: 'e.g., Nike, TD Bank, Northeast Grocers',
    required: false,
  },
  q9: {
    id: 'q9',
    key: 'q9_slowdown',
    section: 'foundation',
    type: 'radio',
    question: 'What slows you down most often?',
    required: true,
    options: [
      { value: 'waiting-for-assets', label: 'Waiting for assets or information' },
      { value: 'unclear-briefs', label: 'Unclear briefs or requirements' },
      { value: 'too-many-revisions', label: 'Too many revision rounds' },
      { value: 'technical-issues', label: 'Technical/software issues' },
      { value: 'context-switching', label: 'Context switching between projects' },
      { value: 'approval-bottlenecks', label: 'Approval bottlenecks' },
      { value: 'other', label: 'Other (specify)' },
    ],
  },
  q10: {
    id: 'q10',
    key: 'q10_knowledge_storage',
    section: 'foundation',
    type: 'radio',
    question: 'When you figure something out, where does that knowledge go?',
    required: true,
    options: [
      { value: 'in-my-head', label: 'I keep it in my head' },
      { value: 'personal-notes', label: 'Personal notes (Notion, docs, etc.)' },
      { value: 'shared-documentation', label: 'Shared team documentation' },
      { value: 'teach-directly', label: 'I teach it to others directly' },
      { value: 'nowhere', label: "It doesn't go anywhere—I solve it again next time" },
    ],
  },
  q11: {
    id: 'q11',
    key: 'q11_research_habits',
    section: 'foundation',
    type: 'textarea',
    question: 'What do you find yourself Googling or asking colleagues about?',
    placeholder: 'e.g., file specs, brand guidelines, software shortcuts, client preferences...',
    required: false,
    validation: { maxLength: 500 },
  },
  q12: {
    id: 'q12',
    key: 'q12_workload',
    section: 'foundation',
    type: 'slider',
    question: 'How would you rate your current workload?',
    required: true,
    validation: { min: 1, max: 10, step: 1 },
    sliderLabels: { min: 'Manageable', max: 'Overwhelming' },
  },
  q13: {
    id: 'q13',
    key: 'q13_friction_types',
    section: 'friction',
    type: 'multi-select',
    question: 'Which of these "friction loops" hit you hardest?',
    description: 'Select all that apply.',
    required: true,
    validation: { minSelections: 1 },
    options: [
      {
        value: 'the-pivot',
        label: 'The Pivot',
        description: 'Last-minute changes that require reworking completed files',
      },
      {
        value: 'the-asset-hunt',
        label: 'The Asset Hunt',
        description: 'Searching through folders, servers, or emails to find the right file',
      },
      {
        value: 'the-versioning-loop',
        label: 'The Versioning Loop',
        description: 'Tracking changes across v1, v2, v2_final, v2_final_FINAL',
      },
      {
        value: 'the-seasonal-rollout',
        label: 'The Seasonal Rollout',
        description: 'Adapting one asset across dozens of sizes, formats, or regions',
      },
      {
        value: 'the-approval-chase',
        label: 'The Approval Chase',
        description: "Following up on reviews that sit in someone's inbox",
      },
      {
        value: 'the-format-shuffle',
        label: 'The Format Shuffle',
        description: 'Converting between file types, color modes, or specs',
      },
      {
        value: 'the-handoff-gap',
        label: 'The Handoff Gap',
        description: 'Miscommunication between teams or roles causing rework',
      },
      { value: 'other', label: 'Other (specify)' },
    ],
  },
  q14: {
    id: 'q14',
    key: 'q14_worst_friction_hours',
    section: 'friction',
    type: 'slider',
    question: 'How many hours per week does your worst friction loop consume?',
    required: true,
    validation: { min: 0, max: 20, step: 0.5 },
    sliderLabels: { min: 'None', max: '20+ hours' },
  },
  q15: {
    id: 'q15',
    key: 'q15_total_friction_hours',
    section: 'friction',
    type: 'slider',
    question: 'Roughly how many total hours per week do ALL friction loops consume?',
    required: true,
    validation: { min: 0, max: 40, step: 1 },
    sliderLabels: { min: 'None', max: '40+ hours' },
  },
  q16: {
    id: 'q16',
    key: 'q16_time_allocation',
    section: 'friction',
    type: 'percentage-allocation',
    question: 'How do you spend your time? (Must total 100%)',
    description: 'Drag sliders or enter percentages.',
    required: true,
    validation: { sumTo: 100 },
    categories: ['Creative / Thinking', 'Production / Execution', 'Communication / Meetings', 'Admin / Searching'],
  },
  q17: {
    id: 'q17',
    key: 'q17_specific_task',
    section: 'friction',
    type: 'textarea',
    question: 'Describe a specific task that eats up your time.',
    placeholder: 'e.g., Every Monday I manually resize 40+ social banners for different platforms...',
    required: false,
    validation: { maxLength: 500 },
  },
  q18: {
    id: 'q18',
    key: 'q18_repeated_task',
    section: 'friction',
    type: 'textarea',
    question: 'What task do you do so often you could do it in your sleep?',
    placeholder: 'e.g., Exporting assets with specific naming conventions...',
    required: false,
    validation: { maxLength: 300 },
  },
  q19: {
    id: 'q19',
    key: 'q19_handoff_pain',
    section: 'friction',
    type: 'textarea',
    question: 'Where do things get stuck waiting on someone else?',
    placeholder: 'e.g., Creative review sits for 3+ days, client feedback delays...',
    required: false,
    validation: { maxLength: 300 },
  },
  q20: {
    id: 'q20',
    key: 'q20_notification_wish',
    section: 'friction',
    type: 'textarea',
    question: 'What do you wish you got notified about automatically?',
    placeholder: 'e.g., When assets are uploaded, when approvals are pending, when deadlines approach...',
    required: false,
    validation: { maxLength: 300 },
  },
  q21: {
    id: 'q21',
    key: 'q21_data_movement',
    section: 'friction',
    type: 'textarea',
    question: 'What information do you manually move between tools?',
    placeholder: 'e.g., Copy data from emails into spreadsheets, update multiple trackers...',
    required: false,
    validation: { maxLength: 300 },
  },
  q22: {
    id: 'q22',
    key: 'q22_documentation_benefit',
    section: 'friction',
    type: 'radio',
    question: 'Who else would benefit if your workflow was documented?',
    required: true,
    options: [
      { value: 'just-me', label: 'Just me' },
      { value: 'immediate-team', label: 'My immediate team' },
      { value: 'other-departments', label: 'Other departments' },
      { value: 'new-hires-freelancers', label: 'New hires / Freelancers' },
      { value: 'everyone', label: 'Everyone at the agency' },
    ],
  },
  q23: {
    id: 'q23',
    key: 'q23_process_feeling',
    section: 'friction',
    type: 'radio',
    question: 'When you finish a project, how do you feel about the process?',
    required: true,
    options: [
      { value: 'proud-both', label: 'Proud of both the work and the process' },
      { value: 'happy-frustrated', label: 'Happy with the output, frustrated with the process' },
      { value: 'process-fine-could-do-better', label: "The process was fine, but I could've done better work" },
      { value: 'relieved', label: "Relieved it's over" },
    ],
  },
  q24: {
    id: 'q24',
    key: 'q24_ai_frequency',
    section: 'ai-sentiment',
    type: 'radio',
    question: 'How often do you currently use AI tools?',
    required: true,
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'few-times-week', label: 'A few times a week' },
      { value: 'few-times-month', label: 'A few times a month' },
      { value: 'rarely', label: 'Rarely' },
      { value: 'never', label: 'Never' },
    ],
  },
  q25: {
    id: 'q25',
    key: 'q25_ai_flavors',
    section: 'ai-sentiment',
    type: 'multi-select',
    question: 'Which "AI flavors" have you tried?',
    description: 'Select all that apply.',
    required: false,
    options: [
      { value: 'the-chat', label: 'The Chat', description: 'ChatGPT, Claude, Gemini for conversation/writing' },
      { value: 'the-canvas', label: 'The Canvas', description: 'Image generation (Midjourney, DALL-E, Firefly)' },
      { value: 'the-voice', label: 'The Voice', description: 'Voice/video AI (ElevenLabs, Synthesia, Descript)' },
      { value: 'the-analyst', label: 'The Analyst', description: 'Data analysis or spreadsheet AI' },
      { value: 'the-researcher', label: 'The Researcher', description: 'Perplexity, Gemini, or AI-powered search' },
      { value: 'the-builder', label: 'The Builder', description: 'No-code tools, AI app builders, vibe coding' },
      { value: 'none', label: 'None of these' },
    ],
  },
  q26: {
    id: 'q26',
    key: 'q26_ai_knowledge',
    section: 'ai-sentiment',
    type: 'slider',
    question: 'How would you rate your AI knowledge?',
    required: true,
    validation: { min: 1, max: 10, step: 1 },
    sliderLabels: { min: "What's a prompt?", max: 'I could teach a workshop' },
  },
  q27: {
    id: 'q27',
    key: 'q27_adoption_speed',
    section: 'ai-sentiment',
    type: 'radio',
    question: 'When it comes to new tools and technology, you typically:',
    required: true,
    options: [
      { value: 'pioneer', label: 'Pioneer', description: 'I try everything first and figure it out' },
      { value: 'fast-follower', label: 'Fast Follower', description: 'I jump in once I see it works' },
      { value: 'pragmatist', label: 'Pragmatist', description: 'I adopt when there\'s clear proof of value' },
      { value: 'skeptic', label: 'Skeptic', description: "I wait until it's mandatory or unavoidable" },
    ],
  },
  q28: {
    id: 'q28',
    key: 'q28_ai_role',
    section: 'ai-sentiment',
    type: 'radio',
    question: 'What role should AI play in creative work?',
    required: true,
    options: [
      { value: 'handle-as-much-as-possible', label: 'AI should handle as much as possible so I can focus on high-level thinking' },
      { value: 'assist-humans-drive', label: 'AI should assist, but humans should drive creative decisions' },
      { value: 'mechanical-only', label: 'AI should only handle purely mechanical/administrative tasks' },
      { value: 'no-place', label: 'AI has no place in creative work' },
    ],
  },
  q29: {
    id: 'q29',
    key: 'q29_ai_concerns',
    section: 'ai-sentiment',
    type: 'multi-select',
    question: 'What concerns you most about AI in the workplace?',
    description: 'Select up to 3.',
    required: false,
    validation: { maxSelections: 3 },
    options: [
      { value: 'brand-accuracy', label: 'Brand accuracy and consistency' },
      { value: 'legal-copyright', label: 'Legal or copyright issues' },
      { value: 'human-touch', label: 'Losing the human touch' },
      { value: 'job-security', label: 'Job security' },
      { value: 'client-perception', label: 'Client perception or pushback' },
      { value: 'data-privacy', label: 'Data privacy' },
      { value: 'quality-control', label: 'Quality control' },
      { value: 'learning-curve', label: 'Learning curve' },
      { value: 'excited', label: "None—I'm excited about it" },
      { value: 'other', label: 'Other (specify)' },
    ],
  },
  q30: {
    id: 'q30',
    key: 'q30_sacred',
    section: 'ai-sentiment',
    type: 'textarea',
    question: "What's \"sacred\" to you?",
    description: 'What part of your work should stay human, no matter what?',
    placeholder: 'e.g., Client relationships, final creative judgment, strategic thinking...',
    required: false,
    validation: { maxLength: 500 },
  },
  q31: {
    id: 'q31',
    key: 'q31_working_ai_tools',
    section: 'ai-sentiment',
    type: 'textarea',
    question: 'Are there any AI tools or prompts that already work well for you?',
    placeholder: 'e.g., I use ChatGPT for first-draft copy, Midjourney for mood boards...',
    required: false,
    validation: { maxLength: 300 },
  },
  q32: {
    id: 'q32',
    key: 'q32_learning_style',
    section: 'ai-sentiment',
    type: 'radio',
    question: 'When you need to learn something new for work, you typically:',
    required: true,
    options: [
      { value: 'youtube-tutorials', label: 'Watch YouTube tutorials' },
      { value: 'documentation', label: 'Read documentation or articles' },
      { value: 'ask-colleague', label: 'Ask a colleague to show me' },
      { value: 'trial-error', label: 'Jump in and figure it out through trial and error' },
      { value: 'structured-course', label: 'Take a structured course' },
    ],
  },
  q33: {
    id: 'q33',
    key: 'q33_magic_button',
    section: 'magic-button',
    type: 'radio',
    question: 'If you could press a magic button, what would it give you?',
    required: true,
    options: [
      { value: 'speed', label: 'Speed', description: 'Get things done faster without sacrificing quality' },
      { value: 'quality', label: 'Quality', description: 'More time to craft and perfect my work' },
      { value: 'organization', label: 'Organization', description: 'Everything in its place, easy to find' },
      { value: 'clarity', label: 'Clarity', description: 'Clear priorities, fewer surprises' },
    ],
  },
  q34: {
    id: 'q34',
    key: 'q34_tedious_task',
    section: 'magic-button',
    type: 'textarea',
    question: "What task do you keep putting off because it's tedious?",
    placeholder: 'e.g., Organizing my files, updating project trackers, cleaning up old versions...',
    required: false,
    validation: { maxLength: 300 },
  },
  q35: {
    id: 'q35',
    key: 'q35_extra_time',
    section: 'magic-button',
    type: 'textarea',
    question: 'If AI gave you 5-10 extra hours per week, what would you do with them?',
    placeholder: 'e.g., More concept exploration, learning new skills, better work-life balance...',
    required: false,
    validation: { maxLength: 300 },
  },
  q36: {
    id: 'q36',
    key: 'q36_ai_success',
    section: 'magic-button',
    type: 'radio',
    question: 'How would you define "AI success" for yourself?',
    required: true,
    options: [
      { value: 'more-done-less-time', label: 'I get more done in less time' },
      { value: 'quality-improves', label: 'The quality of my work improves' },
      { value: 'less-unenjoyable-tasks', label: "I spend less time on tasks I don't enjoy" },
      { value: 'learn-stay-relevant', label: 'I learn new skills and stay relevant' },
      { value: 'work-life-balance', label: 'I achieve better work-life balance' },
    ],
  },
};

// Archetype Configurations
export const ARCHETYPES: Record<string, ArchetypeConfig> = {
  'efficiency-specialist': {
    id: 'efficiency-specialist',
    name: 'Efficiency Specialist',
    description: 'High friction hours, speed priority, production-focused',
    philosophy: 'An Efficiency Specialist optimizes workflows for maximum output, identifying and eliminating bottlenecks with surgical precision.',
    color: '#ef4444',
    icon: 'zap',
  },
  'workflow-architect': {
    id: 'workflow-architect',
    name: 'Workflow Architect',
    description: 'Pioneer adopter, uses multiple AI flavors, sees automation opportunities',
    philosophy: 'A Workflow Architect designs intelligent systems to minimize manual "mud", prioritizing high-value creative orchestration over repetitive technical tasks.',
    color: '#3b82f6',
    icon: 'layout',
  },
  'craft-guardian': {
    id: 'craft-guardian',
    name: 'Craft Guardian',
    description: 'Quality-focused, human touch concerns, protective of creative process',
    philosophy: 'A Craft Guardian balances innovation with tradition, ensuring AI enhances rather than replaces the human elements that make creative work meaningful.',
    color: '#8b5cf6',
    icon: 'shield',
  },
  'curious-explorer': {
    id: 'curious-explorer',
    name: 'Curious Explorer',
    description: 'Interested but early stage, uses chat AI only, learning-oriented',
    philosophy: 'A Curious Explorer approaches AI with open-minded curiosity, eager to discover practical applications while building foundational skills.',
    color: '#22c55e',
    icon: 'compass',
  },
  'steady-guide': {
    id: 'steady-guide',
    name: 'Steady Guide',
    description: 'Adopts when mandatory, prefers known tools, organization priority',
    philosophy: 'A Steady Guide brings stability and reliability to workflows, adopting proven solutions that enhance rather than disrupt established processes.',
    color: '#f97316',
    icon: 'anchor',
  },
  'strategic-navigator': {
    id: 'strategic-navigator',
    name: 'Strategic Navigator',
    description: 'Leadership role, balanced profile, clarity priority',
    philosophy: 'A Strategic Navigator balances team needs with business objectives, steering AI adoption in ways that benefit both individual workflows and organizational goals.',
    color: '#14b8a6',
    icon: 'target',
  },
};

// Tool Configurations
export const TOOLS = [
  {
    name: 'NotebookLM',
    category: 'RAG Research Hub',
    icon: 'book-open',
  },
  {
    name: 'Claude / Gemini / ChatGPT / Perplexity',
    category: 'General AI Assistants',
    icon: 'message-circle',
  },
  {
    name: 'AI Studio',
    category: 'Custom Utility Builder',
    icon: 'code',
  },
  {
    name: 'Claude Cowork',
    category: 'Desktop Agent',
    icon: 'monitor',
  },
  {
    name: 'Custom Agents',
    category: 'Personalized AI Assistants',
    icon: 'bot',
  },
];

// Complexity Tier Colors
export const COMPLEXITY_COLORS = {
  'Quick Win': { bg: 'bg-green-100', text: 'text-green-700', border: 'border-green-200' },
  'Project': { bg: 'bg-orange-100', text: 'text-orange-700', border: 'border-orange-200' },
  'Initiative': { bg: 'bg-purple-100', text: 'text-purple-700', border: 'border-purple-200' },
};
